name: gruvbox-plus-icon-theme
title: Gruvbox Plus Icon Theme
adopt-info: icons
summary: Gruvbox Plus is the icon pack for Linux
description: |
  Gruvbox Plus is the icon pack for Linux, based on and inspired by Suru++, OneDark, 
  Gruvbox icon pack, GruvboxMateria, Papirus, and original Breeze Dark from KDE.

build-base: core24
base: bare
grade: stable
confinement: strict
license: MIT
icon: snap/local/gruvbox-plus.png

platforms:
  all:
    build-on: [amd64]
    build-for: [all]

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Gruvbox-Plus-Dark
        - $SNAP/share/icons/Gruvbox-Plus-Light

parts:
  icons:
    after:
      - utils
    plugin: dump
    source: .
    override-pull: |
      VERSION="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      craftctl set version="$VERSION"
      wget -q "https://github.com/SylEleuth/gruvbox-plus-icon-pack/archive/refs/tags/v${VERSION}.tar.gz" -O - | tar -xz --strip-components=1 -C "$CRAFT_PART_SRC"
    override-build: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      mv $SNAPCRAFT_PART_INSTALL/Numix* $SNAPCRAFT_PART_INSTALL/share/icons/ 2>/dev/null || true
      mv $SNAPCRAFT_PART_INSTALL/Gruvbox* $SNAPCRAFT_PART_INSTALL/share/icons/ 2>/dev/null || true
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Gruvbox-Plus*

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - gtk-update-icon-cache
